# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7c47456a69cb28cb0b87f8ae0d544dc6d2f549bb24a30e1cb444786fc3daa25bef7f2206d378d3565363842186ae574cb86ec2e062e95f511a19c5d837f3aad

test:
  secret_key_base: 836172d2e7760c87cdc215bb88e54d22100caabe180115828f4d3a78ac73161cac88e56425363b5a635f21f520502936f38061c9a252592061b598e2f276a88e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
